// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gslwiqavcqwjtpyeawyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzbHdpcWF2Y3F3anRweWVhd3lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MzY1MDMsImV4cCI6MjA2MzExMjUwM30.n0zxajkUPQn-PbVQNNxD9I_5iQbXCuLaz3QLy-MWe2M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);